keywords: phytoplankton
question: "Compose a comprehensive, evidence‐based overview that discusses the influences of glacial rock 
flour on phytoplankton communities"
model: "gpt-4.1"
vector_store_type: "FAISS"  # InMemory or FAISS
k_chunks: 50  # An int shall be passed
language: "English"
target_audience: "Biologists and glaciologists in search of a review that explains the relationships between Greenlandic 
glacial rock flour and phytoplankton communities"
